language: node_js

node_js:
  - "12"
services:
  - docker
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse'
      key_url: 'https://www.mongodb.org/static/pgp/server-4.2.asc'
    packages:
    - libzmq3-dev
    - mongodb-org
    - mongodb-org-mongos
    - mongodb-org-server
    - mongodb-org-shell
    - mongodb-org-tools

env:
  matrix:
    - SUBPROJECT=catapult-sdk
    - SUBPROJECT=rest
    - SUBPROJECT=spammer

cache: yarn

before_script:
- sudo systemctl start mongod
- sh yarn_setup.sh

script: cd ${SUBPROJECT} && yarn run lint && yarn run test:travis && cd ..

jobs:
  include:
    - stage: docker alpha deploy
      env:
        - SUBPROJECT=rest
      script: /bin/sh docker.sh
      if: branch = master
    - stage: docker release deploy
      env:
        - SUBPROJECT=rest
      script: /bin/sh docker.sh --release
      if: tag IS present
